services:
  deno-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: deno-dev
    working_dir: /app/src
    volumes:
      - .:/app
    env_file:
      - path: ${MB_ENV_FILE:-.env}
    environment:
      # TODO : REMOVE
      - TITLE=My Site in docker !
      - HEADING=Welcome
      - ENV_NAME=development
      - VERSION=1.0.0
    command: >
      watchexec -w /app/src -w /app/template/ -- deno task run

#   go-watcher:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     env_file:
#       - path: ${MB_ENV_FILE:-.env.dev}
#     volumes:
#       - .:/app
#       - go-cache:/go/pkg/mod
#     depends_on:
#       - caddy
#     restart: unless-stopped

#   asset-watcher:
#     image: node:22-alpine
#     working_dir: /app
#     volumes:
#       - .:/app
#       - node-modules:/app/node_modules
#     command: sh -c "npm install && node scripts/dev-assets.js --watch"
#     restart: unless-stopped

#   caddy:
#     image: caddy:2-alpine
#     volumes:
#       - ./dist:/srv
#       - ./server:/etc/caddy
#     ports:
#       - "8007:8007"
#     restart: unless-stopped

# volumes:
#   go-cache:
#   node-modules:
